#!/usr/bin/env python

import json
import sys

class Args:
    def __init__(self):
        self.i = 1

    def get_int(self):
        if len(sys.argv) > self.i:
            a = int(sys.argv[self.i])
            self.i += 1
            return a
        else:
            return None


def main():
    args = Args()
    start = args.get_int()
    end = args.get_int()
    page_min = args.get_int()
    page_max = args.get_int()

    with open('tcp-texts/TCP.json') as f:
        data = json.load(f)

    for e in data["records"]:
        if e["EEBO"] == "":
            continue
        if e["Status"] != "Free":
            continue
        tcp = e["TCP"]
        if start is not None or end is not None:
            try:
                date = int(e["Date"])
            except ValueError:
                continue
            if start is not None and date < start:
                continue
            if end is not None and date > end:
                continue
        if page_min is not None or page_max is not None:
            try:
                pages = int(e["Pages"])
            except ValueError:
                continue
            if page_min is not None and pages < page_min:
                continue
            if page_max is not None and pages > page_max:
                continue
        print tcp

main()
